In [1]:
import numpy as np

In [7]:
A = np.array([[4, 2, 1], [6, 4, 2]])
expand_dims_A = np.expand_dims(A, axis=0)
print(expand_dims_A)
print(expand_dims_A.shape)

[[[4 2 1]
  [6 4 2]]]
(1, 2, 3)


In [8]:
np.random.seed(42)
image = np.random.randint(0, 256, size=(200, 300, 3), dtype=np.uint8)
print(image)

[[[102 220 225]
  [ 95 179  61]
  [234 203  92]
  ...
  [ 41  27  87]
  [102 225  65]
  [170   0 238]]

 [[169 170 213]
  [159  44 250]
  [224 206  61]
  ...
  [162 118  77]
  [228  67  21]
  [ 68  30  64]]

 [[237  26 118]
  [ 62 157 198]
  [  1 151  37]
  ...
  [218 189  51]
  [193 250 243]
  [235  34 180]]

 ...

 [[116 102 228]
  [ 29  75  71]
  [156 133  53]
  ...
  [ 93  45  68]
  [124 238  76]
  [184 185 202]]

 [[216 202 116]
  [146 168 132]
  [236  80  45]
  ...
  [169 145 212]
  [123  50  70]
  [ 11  43  62]]

 [[ 32  52  65]
  [155   2  86]
  [ 83 240  27]
  ...
  [ 30  57 175]
  [ 72  83 171]
  [ 40 114 195]]]


In [9]:
image = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image_extended = np.expand_dims(image, axis=0)
print(image_extended)
print(image_extended.shape)

[[[[145  30 244]
   [107   6 122]
   [201  42  86]
   ...
   [182 113 173]
   [140 196 105]
   [123  60 198]]

  [[221  40 190]
   [175  36 108]
   [ 33   0 106]
   ...
   [ 75 169  71]
   [218 180 159]
   [ 88  16   4]]

  [[141 115 148]
   [211  17 146]
   [118 201  37]
   ...
   [ 10 168 141]
   [136 119 180]
   [134 202  48]]

  ...

  [[105 148  18]
   [178 143 146]
   [249 136  32]
   ...
   [ 80  45 210]
   [182 138  93]
   [ 93 176 230]]

  [[  8  92  85]
   [105 188  47]
   [188 219 100]
   ...
   [117 202 126]
   [171 254  58]
   [ 60 227 231]]

  [[ 90  77 134]
   [121 220 235]
   [ 64 117 152]
   ...
   [ 60 122  47]
   [110 218 233]
   [233  85  89]]]]
(1, 200, 300, 3)


In [10]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)

image1_extended = np.expand_dims(image1, axis=0)
image2_extended = np.expand_dims(image2, axis=0)

images = np.append(image1_extended, image2_extended, axis=0)
print(images)
print(images.shape)

[[[[ 41 115 118]
   [ 84 233 122]
   [  9 233 198]
   ...
   [ 37  99 209]
   [211 120 126]
   [ 59  79  35]]

  [[136 156 232]
   [107 217 177]
   [129 224  85]
   ...
   [132  46 214]
   [107 200 163]
   [121  45 198]]

  [[ 58  69 203]
   [ 20  13 211]
   [254 145  72]
   ...
   [  6 183 128]
   [159 139  20]
   [217 117  31]]

  ...

  [[178  96 176]
   [178 151  78]
   [175 147 177]
   ...
   [169 200  37]
   [  9 171  29]
   [145 143  28]]

  [[189 185 126]
   [ 59  76 205]
   [  9 136  25]
   ...
   [ 62  31 235]
   [104 133 186]
   [154  50 165]]

  [[157 209 251]
   [181 230  48]
   [ 21 223 136]
   ...
   [ 76  88 111]
   [211 188  36]
   [ 23 111 239]]]


 [[[ 81  84 180]
   [239 195  87]
   [ 10 247 246]
   ...
   [ 49 136  91]
   [136 192 105]
   [  4 122 161]]

  [[121 115 195]
   [ 18   3 184]
   [253 169 244]
   ...
   [ 92 136 206]
   [ 89  89 113]
   [184   1  81]]

  [[198 236  19]
   [210  50 104]
   [ 12  47 217]
   ...
   [205  24 154]
   [241 227 167]
   [208 134

In [11]:
A = np.array([[[1, 2, 3], [6, 3, 2]]])
print(np.squeeze(A))

[[1 2 3]
 [6 3 2]]


In [12]:
A = np.array([[0.4], [0.9], [0.5], [0.6]])
print(np.squeeze(A))

[0.4 0.9 0.5 0.6]


In [13]:
A = np.array([[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]])
print(A[:, ::-1])

[[ 3  2  1  0]
 [ 7  6  5  4]
 [11 10  9  8]]


In [14]:
A = np.arange(0, 12, dtype="int").reshape(3, -1)
print(A[::-1, ::-1])

[[11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [15]:
np.random.seed(42)

image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

print(image[0])

[[102 220 225]
 [ 95 179  61]
 [234 203  92]
 [  3  98 243]
 [ 14 149 245]
 [ 46 106 244]
 [ 99 187  71]
 [212 153 199]
 [188 174  65]
 [153  20  44]]


In [21]:
image = np.random.randint(low=0, high=256, size=(10, 10, 3), dtype=np.uint8)

result = image[:5, :5, :]
print(result.shape)

(5, 5, 3)
