In [1]:
import numpy as np

In [9]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

# print((A + B) / 2)
print(np.divide(np.add(A, B), 2))

[[3.5 3.5 5.5 3.5]
 [5.5 3.  1.5 5.5]]


In [11]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5], [6, 3, 1, 6]])

# print(A * B)
print(np.multiply(A, B))

[[12 12 18 10]
 [30  9  2 30]]


In [12]:
A = np.array([[3, 4, 9, 2], [5, 3, 2, 5]])
print(np.sqrt(A))

[[1.73205081 2.         3.         1.41421356]
 [2.23606798 1.73205081 1.41421356 2.23606798]]


In [15]:
A = np.linspace(0, np.pi / 2, 20)
B = np.full(shape=(20,), fill_value=1, dtype="float")

print(np.allclose(np.sin(A) ** 2 + np.cos(A) ** 2, B))

True


In [17]:
A = np.array([[2, 3], [-4, 2], [5, 0]])
B = np.array([[4, 3, 2], [-1, 0, 2]])

# print(A @ B)
print(np.dot(A, B))

[[  5   6  10]
 [-18 -12  -4]
 [ 20  15  10]]


In [18]:
A = np.array([[-2, 0, 4], [5, 2, -1], [-4, 2, 4]])

print(np.linalg.det(A))

51.999999999999986


In [21]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[-9.24621125 -3.          7.24621125]
[[-6.26164716e-01 -8.94427191e-01  8.90159406e-01]
 [-3.13082358e-01  2.82399734e-16  4.45079703e-01]
 [ 7.14070855e-01  4.47213595e-01 -9.75719719e-02]]


In [22]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
print(np.linalg.inv(A))

[[-0.21393035  0.75621891  0.23880597]
 [ 0.05970149  0.04477612  0.11940299]
 [ 0.09950249 -0.25870647 -0.13432836]]


In [23]:
A = np.array([[5, 8, 16], [4, 1, 8], [-4, 4, -11]])
print(np.trace(A))

-5


In [24]:
A = np.array([[2, 0], [4, 2], [5, 3], [4, 2]])
B = np.array([[4, 0, 2, 1, 1, 0, 2, 9]])

print(A @ (B.reshape(2, -1)))

[[ 8  0  4  2]
 [18  0 12 22]
 [23  0 16 32]
 [18  0 12 22]]
