In [1]:
import numpy as np

In [3]:
np.save("array.npy", np.arange(12, dtype="int").reshape(3, 4))
A = np.load("array.npy")
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [5]:
A = np.arange(12, dtype="int").reshape(3, 4)
np.savetxt("array.txt", A, fmt="%0.2f")
B = np.loadtxt("array.txt")
print(B)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]


In [6]:
A = np.arange(12, dtype="int").reshape(3, 4)
print(A.tolist())

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]


In [23]:
A = np.arange(12, dtype="int").reshape(3, 4)
# print(A[:, ::-1])
print(A[::-1])

[[ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [16]:
A = np.ones(shape=(4, 4), dtype="float")

print(np.pad(A, 1, constant_values=0))

[[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [24]:
A = np.zeros(shape=(6, 6), dtype="int")
A[::2, ::2] = 10
A[1::2, ::2] = 5
print(A)

[[10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]
 [10  0 10  0 10  0]
 [ 5  0  5  0  5  0]]


In [27]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2], [0, 5, 2, 6]])
print(np.append(A, B, axis=0))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [ 4  3  7  2]
 [ 0  5  2  6]]


In [28]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3], [2, 8, 0, 9]])

print(np.intersect1d(A, B))

[0 2 3]


In [29]:
A = np.array([[5, 1, 2, 1, 2], [9, 1, 9, 7, 5], [4, 1, 5, 7, 9]])

print(np.unique(A))

[1 2 4 5 7 9]


In [32]:
A = np.array([[0.4, 0.3, 0.3], [0.1, 0.1, 0.8], [0.2, 0.5, 0.3]])

print(np.argmax(A, axis=1))

[0 2 1]
