In [1]:
import numpy as np

In [2]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])

print(np.sort(A, axis=1))
print(np.sort(A, axis=0))

[[ 3.49  4.99  9.99]
 [ 1.99  4.99  9.99]
 [ 2.39  7.29 14.99]]
[[ 1.99  2.39  4.99]
 [ 4.99  3.49  7.29]
 [14.99  9.99  9.99]]


In [3]:
A = np.array([[4.99, 3.49, 9.99], [1.99, 9.99, 4.99], [14.99, 2.39, 7.29]])
print(A[A > 8])

[ 9.99  9.99 14.99]


In [7]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

# A[A > 10] = 10.0
print(np.where(A > 10, 10.0, A))

[[ 4.99  3.49  9.99]
 [ 1.99  9.99 10.  ]
 [10.    2.39  7.29]]


In [8]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)
print(np.ravel(A))

[ 4.99  3.49  9.99  1.99  9.99 14.99 14.99  2.39  7.29]


In [9]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

print(np.zeros_like(A))

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
A = np.array(
    [
        [4.99, 3.49, 9.99],
        [1.99, 9.99, 14.99],
        [14.99, 2.39, 7.29],
    ]
)

print(np.full_like(A, 9.99))

[[9.99 9.99 9.99]
 [9.99 9.99 9.99]
 [9.99 9.99 9.99]]


In [11]:
print(np.tri(5))

[[1. 0. 0. 0. 0.]
 [1. 1. 0. 0. 0.]
 [1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0.]
 [1. 1. 1. 1. 1.]]


In [13]:
# print(np.random.randint(0, 10, (2, 3, 4)))

A = np.array(
    [
        [[4, 5, 4, 2], [6, 3, 5, 1], [5, 2, 1, 2]],
        [[7, 2, 3, 1], [6, 2, 0, 9], [0, 1, 9, 1]],
    ]
)
print(A)

[[[4 5 4 2]
  [6 3 5 1]
  [5 2 1 2]]

 [[7 2 3 1]
  [6 2 0 9]
  [0 1 9 1]]]


In [14]:
image = np.random.randint(0, 256, size=(200, 300), dtype=np.uint8)
print(image)

[[ 69  83  56 ... 111 158 176]
 [ 90 127 147 ...  50 121 206]
 [ 36  44 102 ...  67 164 199]
 ...
 [ 77  80   2 ... 149 190  25]
 [ 86  41 194 ... 243  36  30]
 [113  84  34 ... 194 248 151]]


In [15]:
image = np.random.randint(low=0, high=256, size=(200, 300), dtype=np.uint8)
image_sorted = np.sort(image, axis=1)
print(image_sorted)

[[  0   1   2 ... 252 253 253]
 [  0   1   1 ... 253 253 255]
 [  2   2   2 ... 250 255 255]
 ...
 [  0   3   3 ... 251 252 253]
 [  0   0   1 ... 253 253 254]
 [  0   0   0 ... 255 255 255]]
