In [10]:
import numpy as np

np.random.seed(42)

In [5]:
A = np.array(
    [
        ["id", "price"],
        ["001", 14.99],
        ["002", 4.99],
        ["003", 7.99],
        ["004", 2.49],
        ["005", 1.49],
    ]
)
np.random.shuffle(A[1:])
print(A)

[['id' 'price']
 ['003' '7.99']
 ['005' '1.49']
 ['004' '2.49']
 ['001' '14.99']
 ['002' '4.99']]


In [8]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
print(np.argsort(A))

[5 2 1 0 4 3]


In [16]:
np.random.seed(42)
A = np.random.randn(10, 8)
print(np.round(A, 3))

[[ 0.497 -0.138  0.648  1.523 -0.234 -0.234  1.579  0.767]
 [-0.469  0.543 -0.463 -0.466  0.242 -1.913 -1.725 -0.562]
 [-1.013  0.314 -0.908 -1.412  1.466 -0.226  0.068 -1.425]
 [-0.544  0.111 -1.151  0.376 -0.601 -0.292 -0.602  1.852]
 [-0.013 -1.058  0.823 -1.221  0.209 -1.96  -1.328  0.197]
 [ 0.738  0.171 -0.116 -0.301 -1.479 -0.72  -0.461  1.057]
 [ 0.344 -1.763  0.324 -0.385 -0.677  0.612  1.031  0.931]
 [-0.839 -0.309  0.331  0.976 -0.479 -0.186 -1.106 -1.196]
 [ 0.813  1.356 -0.072  1.004  0.362 -0.645  0.361  1.538]
 [-0.036  1.565 -2.62   0.822  0.087 -0.299  0.092 -1.988]]


In [17]:
print(np.roots([4, 5, 1]))

[-1.   -0.25]


In [18]:
print(np.roots([2, 4, -5, 1]))
print(np.roots([2, 0, -5, 1]))

[-2.91610583  0.65388685  0.26221898]
[-1.67298165  1.46961743  0.20336421]


In [20]:
W = np.array([0, 4, 5, 1])
Q = np.array([2, 4, -5, 1])

print(np.polyadd(W, Q))
print(np.polysub(W, Q))
print(np.polymul(W, Q))
print(np.polyadd(W, 2 * Q))

[2 8 0 2]
[-2  0 10  0]
[  8  26   2 -17   0   1]
[ 4 12 -5  3]


In [21]:
A = np.array([[-4, 3, 0, 1, -5], [6, -4, -2, 1, 3]])
print(np.sign(A))

[[-1  1  0  1 -1]
 [ 1 -1 -1  1  1]]


In [32]:
print(np.arange("2021-01-01", "2021-02-01", dtype="datetime64[D]"))

['2021-01-01' '2021-01-02' '2021-01-03' '2021-01-04' '2021-01-05'
 '2021-01-06' '2021-01-07' '2021-01-08' '2021-01-09' '2021-01-10'
 '2021-01-11' '2021-01-12' '2021-01-13' '2021-01-14' '2021-01-15'
 '2021-01-16' '2021-01-17' '2021-01-18' '2021-01-19' '2021-01-20'
 '2021-01-21' '2021-01-22' '2021-01-23' '2021-01-24' '2021-01-25'
 '2021-01-26' '2021-01-27' '2021-01-28' '2021-01-29' '2021-01-30'
 '2021-01-31']


In [34]:
print(np.arange("2021-01", "2022-01", dtype="datetime64[M]").reshape(4, -1))

[['2021-01' '2021-02' '2021-03']
 ['2021-04' '2021-05' '2021-06']
 ['2021-07' '2021-08' '2021-09']
 ['2021-10' '2021-11' '2021-12']]


In [37]:
print(np.datetime64("today"))

2024-05-20
