In [21]:
# Exo 0
import numpy as np

print(np.__version__)

1.24.1


In [22]:
# Exo 1
import numpy as np

A = np.array([[3, 2, 1, 4], [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4], [5, 2, 0, 6]])

C = np.array([[True, False, False], [True, True, True]])

D = np.array([0.1, 0.3])

for name, array in zip(list("ABCD"), [A, B, C, D]):
    print(f"{name}: {np.all(array)}")

A: True
B: False
C: False
D: True


In [23]:
# Exo 2
import numpy as np

A = np.array([[3, 2, 1, 4], [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4], [5, 2, 0, 6]])

C = np.array([[True, False, False], [True, True, True]])

for name, array in zip(list("ABC"), [A, B, C]):
    print(f"{name}: {np.all(array, axis=1)}")

A: [ True  True]
B: [ True False]
C: [False  True]


In [24]:
# Exo 3
import numpy as np

A = np.array([[0, 0, 0], [0, 0, 0]])

B = np.array([[0, 0, 0], [0, 1, 0]])

C = np.array([[False, False, False], [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list("ABCD"), [A, B, C, D]):
    print(f"{name}: {np.any(array)}")

A: False
B: True
C: True
D: True


In [25]:
# Exo 4
import numpy as np


A = np.array([[0, 0, 0], [0, 0, 0]])

B = np.array([[0, 0, 0], [0, 1, 0]])

C = np.array([[False, False, False], [True, False, False]])

D = np.array([[0.1, 0.0]])

for name, array in zip(list("ABCD"), [A, B, C, D]):
    print(f"{name}: {np.any(array,axis=0)}")

A: [False False False]
B: [False  True False]
C: [ True False False]
D: [ True False]


In [27]:
# Exo 5
import numpy as np

A = np.array([[3, 2, 1, np.nan], [5, np.nan, 1, 6]])

print(np.isnan(A))

[[False False False  True]
 [False  True False False]]


In [28]:
# Exo 6

import numpy as np


A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

print(np.allclose(A, B))

True


In [30]:
# Exo 7
import numpy as np


A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])

print(A == B)

print(np.equal(A, B))

[False False  True]
[False False  True]


In [32]:
# Exo 8

import numpy as np


A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])

print(A > B)
print(np.greater(A, B))

[ True False False False]
[ True False False False]


In [36]:
# Exo 9

print(np.zeros(shape=(4, 4), dtype="int"))

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [37]:
# Exo 10
print(np.full(shape=(10, 10), fill_value=255, dtype="float"))
print(np.ones(shape=(10, 10), dtype="float") * 255)

[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]]
[[255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255. 255.]
 [255. 255. 255. 255. 255. 255. 255. 255. 255