In [2]:
import numpy as np

In [36]:
wig_games_raw = """Profile    Time    Course    Change    Change%    Ref.    Open    Low    High    Volume    Turn    Share
11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034%
CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618%
CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855%
PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638%
TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%"""

lines = wig_games_raw.splitlines()
lines = [line.split("    ") for line in lines]
wig_games = np.array(lines, dtype="str")
wig_games = np.char.replace(wig_games, " ", "")
print(wig_games)

[['Profile' 'Time' 'Course' 'Change' 'Change%' 'Ref.' 'Open' 'Low' 'High'
  'Volume' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '+8.00' '(+2.09%)' '383.00' '383.50'
  '383.00' '394.00' '12784' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '+5.30' '(+1.59%)' '334.20'
  '338.30' '337.00' '344.20' '233059' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '-0.012' '(-1.59%)' '0.754' '0.772'
  '0.730' '0.772' '1311078' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '+18.00' '(+4.87%)' '369.50'
  '374.00' '373.00' '388.00' '33206' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '+22.50' '(+6.88%)' '327.00'
  '332.00' '330.00' '353.50' '39793' '13697060' '28.855%']]


In [3]:
wig_games = np.array(
    [
        [
            "Profile",
            "Time",
            "Course",
            "Open",
            "Low",
            "High",
            "Turn",
            "Share",
        ],
        [
            "11B(11BIT)",
            "17kwi17:01",
            "391.00",
            "383.50",
            "383.00",
            "394.00",
            "4994874",
            "19.034%",
        ],
        [
            "CDR(CDPROJEKT)",
            "17kwi17:01",
            "339.50",
            "338.30",
            "337.00",
            "344.20",
            "79245368",
            "39.618%",
        ],
        [
            "CIG(CIGAMES)",
            "17kwi17:03",
            "0.742",
            "0.772",
            "0.730",
            "0.772",
            "971459",
            "1.855%",
        ],
        [
            "PLW(PLAYWAY)",
            "17kwi17:03",
            "387.50",
            "374.00",
            "373.00",
            "388.00",
            "12661786",
            "10.638%",
        ],
        [
            "TEN(TSGAMES)",
            "17kwi17:02",
            "349.50",
            "332.00",
            "330.00",
            "353.50",
            "13697060",
            "28.855%",
        ],
    ],
    dtype="<U14",
)

np.set_printoptions(linewidth=160, suppress=True)
np.savetxt(fname="wig_games.csv", X=wig_games, fmt="%s", delimiter=",")
wig_games_new = np.loadtxt(fname="wig_games.csv", delimiter=",", dtype=str)
print(wig_games_new)

[['Profile' 'Time' 'Course' 'Open' 'Low' 'High' 'Turn' 'Share']
 ['11B(11BIT)' '17kwi17:01' '391.00' '383.50' '383.00' '394.00' '4994874' '19.034%']
 ['CDR(CDPROJEKT)' '17kwi17:01' '339.50' '338.30' '337.00' '344.20' '79245368' '39.618%']
 ['CIG(CIGAMES)' '17kwi17:03' '0.742' '0.772' '0.730' '0.772' '971459' '1.855%']
 ['PLW(PLAYWAY)' '17kwi17:03' '387.50' '374.00' '373.00' '388.00' '12661786' '10.638%']
 ['TEN(TSGAMES)' '17kwi17:02' '349.50' '332.00' '330.00' '353.50' '13697060' '28.855%']]


In [8]:
playway_raw = """Date,Open,High,Low,Close,Volume
2020-03-02,305,324.5,283.5,310,64081
2020-03-03,325.5,340.5,320,340.5,55496
2020-03-04,324,340.5,315,330,36152
2020-03-05,344,344,310,315,35992
2020-03-06,306.5,307,291,305,32539
2020-03-09,274,291,250,258,79402
2020-03-10,278,284.5,256,264,35700
2020-03-11,270,270,238.5,245,60445
2020-03-12,218,228,196,197,94031
2020-03-13,210,229,198.8,211,100412
2020-03-16,205,248,197.8,240.5,50659
2020-03-17,245,269,232.5,264,99480
2020-03-18,264,280,251,270,70136
2020-03-19,267,280,267,279.5,30732
2020-03-20,297.5,307,280,280.5,43426
2020-03-23,274,289,258,285,37098
2020-03-24,305,309,296.5,309,31939
2020-03-25,313,330,295,304,46724
2020-03-26,300,309,295.5,300,27213
2020-03-27,302,306.5,290,296,13466
2020-03-30,299,300,287,300,10316
2020-03-31,302.5,309,302,306.5,15698"""

lines = playway_raw.split()
lines_with_column = np.array([line.split(",") for line in lines])
print(lines_with_column)

[['Date' 'Open' 'High' 'Low' 'Close' 'Volume']
 ['2020-03-02' '305' '324.5' '283.5' '310' '64081']
 ['2020-03-03' '325.5' '340.5' '320' '340.5' '55496']
 ['2020-03-04' '324' '340.5' '315' '330' '36152']
 ['2020-03-05' '344' '344' '310' '315' '35992']
 ['2020-03-06' '306.5' '307' '291' '305' '32539']
 ['2020-03-09' '274' '291' '250' '258' '79402']
 ['2020-03-10' '278' '284.5' '256' '264' '35700']
 ['2020-03-11' '270' '270' '238.5' '245' '60445']
 ['2020-03-12' '218' '228' '196' '197' '94031']
 ['2020-03-13' '210' '229' '198.8' '211' '100412']
 ['2020-03-16' '205' '248' '197.8' '240.5' '50659']
 ['2020-03-17' '245' '269' '232.5' '264' '99480']
 ['2020-03-18' '264' '280' '251' '270' '70136']
 ['2020-03-19' '267' '280' '267' '279.5' '30732']
 ['2020-03-20' '297.5' '307' '280' '280.5' '43426']
 ['2020-03-23' '274' '289' '258' '285' '37098']
 ['2020-03-24' '305' '309' '296.5' '309' '31939']
 ['2020-03-25' '313' '330' '295' '304' '46724']
 ['2020-03-26' '300' '309' '295.5' '300' '27213']
 ['2

In [14]:
playway = np.array(
    [
        ["Date", "Open", "High", "Low", "Close", "Volume"],
        ["2020-03-02", "305", "324.5", "283.5", "310", "64081"],
        ["2020-03-03", "325.5", "340.5", "320", "340.5", "55496"],
        ["2020-03-04", "324", "340.5", "315", "330", "36152"],
        ["2020-03-05", "344", "344", "310", "315", "35992"],
        ["2020-03-06", "306.5", "307", "291", "305", "32539"],
        ["2020-03-09", "274", "291", "250", "258", "79402"],
        ["2020-03-10", "278", "284.5", "256", "264", "35700"],
        ["2020-03-11", "270", "270", "238.5", "245", "60445"],
        ["2020-03-12", "218", "228", "196", "197", "94031"],
        ["2020-03-13", "210", "229", "198.8", "211", "100412"],
        ["2020-03-16", "205", "248", "197.8", "240.5", "50659"],
        ["2020-03-17", "245", "269", "232.5", "264", "99480"],
        ["2020-03-18", "264", "280", "251", "270", "70136"],
        ["2020-03-19", "267", "280", "267", "279.5", "30732"],
        ["2020-03-20", "297.5", "307", "280", "280.5", "43426"],
        ["2020-03-23", "274", "289", "258", "285", "37098"],
        ["2020-03-24", "305", "309", "296.5", "309", "31939"],
        ["2020-03-25", "313", "330", "295", "304", "46724"],
        ["2020-03-26", "300", "309", "295.5", "300", "27213"],
        ["2020-03-27", "302", "306.5", "290", "296", "13466"],
        ["2020-03-30", "299", "300", "287", "300", "10316"],
        ["2020-03-31", "302.5", "309", "302", "306.5", "15698"],
    ],
    dtype="<U10",
)

dates_deleted = np.delete(playway, [0], axis=1)
header_deleted = dates_deleted[1:, :].astype(float)
print(header_deleted)

[[   305.     324.5    283.5    310.   64081. ]
 [   325.5    340.5    320.     340.5  55496. ]
 [   324.     340.5    315.     330.   36152. ]
 [   344.     344.     310.     315.   35992. ]
 [   306.5    307.     291.     305.   32539. ]
 [   274.     291.     250.     258.   79402. ]
 [   278.     284.5    256.     264.   35700. ]
 [   270.     270.     238.5    245.   60445. ]
 [   218.     228.     196.     197.   94031. ]
 [   210.     229.     198.8    211.  100412. ]
 [   205.     248.     197.8    240.5  50659. ]
 [   245.     269.     232.5    264.   99480. ]
 [   264.     280.     251.     270.   70136. ]
 [   267.     280.     267.     279.5  30732. ]
 [   297.5    307.     280.     280.5  43426. ]
 [   274.     289.     258.     285.   37098. ]
 [   305.     309.     296.5    309.   31939. ]
 [   313.     330.     295.     304.   46724. ]
 [   300.     309.     295.5    300.   27213. ]
 [   302.     306.5    290.     296.   13466. ]
 [   299.     300.     287.     300.   1

In [15]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

print(np.round(np.average(playway_values, axis=0), 2))

[  283.14   295.25   268.69   282.3  48688.05]


In [41]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0],
        [324.0, 340.5, 315.0, 330.0, 36152.0],
        [344.0, 344.0, 310.0, 315.0, 35992.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0],
        [270.0, 270.0, 238.5, 245.0, 60445.0],
        [218.0, 228.0, 196.0, 197.0, 94031.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0],
        [205.0, 248.0, 197.8, 240.5, 50659.0],
        [245.0, 269.0, 232.5, 264.0, 99480.0],
        [264.0, 280.0, 251.0, 270.0, 70136.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0],
        [313.0, 330.0, 295.0, 304.0, 46724.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0],
        [302.0, 306.5, 290.0, 296.0, 13466.0],
        [299.0, 300.0, 287.0, 300.0, 10316.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0],
    ]
)

max_min_diff = np.max(playway_values[:, :-1], axis=1) - np.min(
    playway_values[:, :-1], axis=1
)
max_min_diff = np.expand_dims(max_min_diff, axis=1)
print(np.concatenate((playway_values, max_min_diff), axis=1))

(22, 1)
[[   305.     324.5    283.5    310.   64081.      41. ]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   324.     340.5    315.     330.   36152.      25.5]
 [   344.     344.     310.     315.   35992.      34. ]
 [   306.5    307.     291.     305.   32539.      16. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   278.     284.5    256.     264.   35700.      28.5]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   210.     229.     198.8    211.  100412.      30.2]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   264.     280.     251.     270.   70136.      29. ]
 [   267.     280.     267.     279.5  30732.      13. ]
 [   297.5    307.     280.     280.5  43426.      27. ]
 [   274.     289.     258.     285.   37098.      31. ]
 [   305.     309.     296.5    309.   31939.      12.5]
 [   313.     330.     

In [42]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

print(playway_values[playway_values[:, 3] > 300.0])

[[  305.    324.5   283.5   310.  64081.     41. ]
 [  325.5   340.5   320.    340.5 55496.     20.5]
 [  324.    340.5   315.    330.  36152.     25.5]
 [  344.    344.    310.    315.  35992.     34. ]
 [  306.5   307.    291.    305.  32539.     16. ]
 [  305.    309.    296.5   309.  31939.     12.5]
 [  313.    330.    295.    304.  46724.     35. ]
 [  302.5   309.    302.    306.5 15698.      7. ]]


In [48]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

sort_values_index = np.argsort(playway_values[:, 4], axis=0)[::-1]
print(playway_values[sort_values_index][:10, :])

[[   210.     229.     198.8    211.  100412.      30.2]
 [   245.     269.     232.5    264.   99480.      36.5]
 [   218.     228.     196.     197.   94031.      32. ]
 [   274.     291.     250.     258.   79402.      41. ]
 [   264.     280.     251.     270.   70136.      29. ]
 [   305.     324.5    283.5    310.   64081.      41. ]
 [   270.     270.     238.5    245.   60445.      31.5]
 [   325.5    340.5    320.     340.5  55496.      20.5]
 [   205.     248.     197.8    240.5  50659.      50.2]
 [   313.     330.     295.     304.   46724.      35. ]]


In [63]:
playway_values = np.array(
    [
        [305.0, 324.5, 283.5, 310.0, 64081.0, 41.0],
        [325.5, 340.5, 320.0, 340.5, 55496.0, 20.5],
        [324.0, 340.5, 315.0, 330.0, 36152.0, 25.5],
        [344.0, 344.0, 310.0, 315.0, 35992.0, 34.0],
        [306.5, 307.0, 291.0, 305.0, 32539.0, 16.0],
        [274.0, 291.0, 250.0, 258.0, 79402.0, 41.0],
        [278.0, 284.5, 256.0, 264.0, 35700.0, 28.5],
        [270.0, 270.0, 238.5, 245.0, 60445.0, 31.5],
        [218.0, 228.0, 196.0, 197.0, 94031.0, 32.0],
        [210.0, 229.0, 198.8, 211.0, 100412.0, 30.2],
        [205.0, 248.0, 197.8, 240.5, 50659.0, 50.2],
        [245.0, 269.0, 232.5, 264.0, 99480.0, 36.5],
        [264.0, 280.0, 251.0, 270.0, 70136.0, 29.0],
        [267.0, 280.0, 267.0, 279.5, 30732.0, 13.0],
        [297.5, 307.0, 280.0, 280.5, 43426.0, 27.0],
        [274.0, 289.0, 258.0, 285.0, 37098.0, 31.0],
        [305.0, 309.0, 296.5, 309.0, 31939.0, 12.5],
        [313.0, 330.0, 295.0, 304.0, 46724.0, 35.0],
        [300.0, 309.0, 295.5, 300.0, 27213.0, 13.5],
        [302.0, 306.5, 290.0, 296.0, 13466.0, 16.5],
        [299.0, 300.0, 287.0, 300.0, 10316.0, 13.0],
        [302.5, 309.0, 302.0, 306.5, 15698.0, 7.0],
    ]
)

# isCloseHigherOpenIndex = playway_values[:, 3] > playway_values[:, 0]
# playway_values = np.concatenate(
#     (playway_values, np.expand_dims(isCloseHigherOpenIndex.astype(float), axis=1)),
#     axis=1,
# )

isCloseHigherOpenIndex = playway_values[:, [3]] > playway_values[:, [0]]
playway_values = np.concatenate(
    (playway_values, isCloseHigherOpenIndex),
    axis=1,
)

print(playway_values)

[[   305.     324.5    283.5    310.   64081.      41.       1. ]
 [   325.5    340.5    320.     340.5  55496.      20.5      1. ]
 [   324.     340.5    315.     330.   36152.      25.5      1. ]
 [   344.     344.     310.     315.   35992.      34.       0. ]
 [   306.5    307.     291.     305.   32539.      16.       0. ]
 [   274.     291.     250.     258.   79402.      41.       0. ]
 [   278.     284.5    256.     264.   35700.      28.5      0. ]
 [   270.     270.     238.5    245.   60445.      31.5      0. ]
 [   218.     228.     196.     197.   94031.      32.       0. ]
 [   210.     229.     198.8    211.  100412.      30.2      1. ]
 [   205.     248.     197.8    240.5  50659.      50.2      1. ]
 [   245.     269.     232.5    264.   99480.      36.5      1. ]
 [   264.     280.     251.     270.   70136.      29.       1. ]
 [   267.     280.     267.     279.5  30732.      13.       1. ]
 [   297.5    307.     280.     280.5  43426.      27.       0. ]
 [   274. 